/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package correio.gui;

import correio.core.ServidorDeMensagens;
import correio.core.Usuario;
import correio.utils.RMIUtils;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author filipe
 */
public class TerminalServidor extends javax.swing.JFrame {

    private class RegistroDeUsuarioPanel extends JPanel {
        private JButton botaoRemover;
        private JLabel labelInfo;
        private String info;

        public RegistroDeUsuarioPanel(String username, int unreadMessages) {
            info = "Usuário: " + username + " | Mensagens não lidas: " + unreadMessages;
            botaoRemover = new JButton("Remover");
            botaoRemover.addActionListener((ActionEvent e) -> {
                servidor.removerUsuario(username);
            });
            
            labelInfo = new JLabel(info);
            setLayout(new FlowLayout());
            add(botaoRemover);
            add(labelInfo);
            pack();
        }
    }
    
    private ServidorDeMensagens servidor;
    
    public TerminalServidor(String hostname) {
        initComponents();
        iniciarServidor(hostname);
        setLocationRelativeTo(null);
        corrigirTamanhoJanela();
    }
    
    private void corrigirTamanhoJanela() {
        setSize(500, 600);
    }
    
    private void iniciarServidor(String hostname) {
        servidor = new ServidorDeMensagens();
        servidor.addServidorListener(() -> {
            carregarUsuarios();
        });
        RMIUtils.registrarServicoRMI(servidor, hostname);
        carregarUsuarios();
    }
    
    private void carregarUsuarios() {
        List<Usuario> usuarios = servidor.getUsuarios();
        painelUsers.removeAll();
        for (Usuario usuario : usuarios) {
            RegistroDeUsuarioPanel panel = new RegistroDeUsuarioPanel(usuario.getUserName(), usuario.getQtdMensagens());
            painelUsers.add(panel);
        }
        revalidate();
        repaint();
        corrigirTamanhoJanela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        painelUsers = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Servidor do Correio");

        painelUsers.setLayout(new javax.swing.BoxLayout(painelUsers, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(painelUsers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painelUsers;
    // End of variables declaration//GEN-END:variables
}
