/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package correio.gui;

import correio.core.ServidorDeMensagens;
import correio.core.ServidorListener;
import correio.core.Usuario;
import correio.utils.RMIUtils;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author filipe
 */
public class TerminalServidor extends javax.swing.JFrame {

    private class RegistroDeUsuarioPanel extends JPanel {
        private JButton botaoRemover;
        private JLabel labelInfo;
        private String info;

        public RegistroDeUsuarioPanel(String username, int unreadMessages) {
            info = "Usuário: " + username + " | Mensagens não lidas: " + unreadMessages;
            botaoRemover = new JButton("Remover");
            botaoRemover.addActionListener((ActionEvent e) -> {
                servidor.removerUsuario(username);
            });
            
            labelInfo = new JLabel(info);
            setLayout(new FlowLayout());
            add(botaoRemover);
            add(labelInfo);
            pack();
        }
    }
    
    private ServidorDeMensagens servidor;
    
    public TerminalServidor(String hostname) {
        initComponents();
        iniciarServidor(hostname);
        setLocationRelativeTo(null);
        corrigirTamanhoJanela();
    }
    
    private void corrigirTamanhoJanela() {
        setSize(400, 600);
    }
    
    private void iniciarServidor(String hostname) {
        servidor = new ServidorDeMensagens(hostname);
        servidor.addServidorListener(() -> {
            carregarUsuarios();
        });
        RMIUtils.registrarServicoRMI(servidor, hostname);
    }
    
    private void carregarUsuarios() {
        List<Usuario> usuarios = servidor.getUsuarios();
        painelUsers.removeAll();
        for (Usuario usuario : usuarios) {
            RegistroDeUsuarioPanel panel = new RegistroDeUsuarioPanel(usuario.getUserName(), usuario.getQtdMensagens());
            painelUsers.add(panel);
        }
        revalidate();
        repaint();
        corrigirTamanhoJanela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        painelUsers = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelUsers.setLayout(new javax.swing.BoxLayout(painelUsers, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(painelUsers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TerminalServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TerminalServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TerminalServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TerminalServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TerminalServidor("127.0.0.1").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painelUsers;
    // End of variables declaration//GEN-END:variables
}
